### ISSUE TITLE
Kibana Dashboard

### ISSUE THREAD

**Issue by coolpalani** [flant/kubernetes-efk#1]
Did you create any dashboard after collected metrics from fluentd , Elasticsearch.
I am trying to create a visualize dashboard in kibana but couldn't get proper one.
If you share some insights , it would be great

**Comment by zuzzas** [comment]
I'm afraid, it a dead repository, since we've moved to our [own solution](https://github.com/flant/loghouse). We'll probably delete it soon.

**Comment by coolpalani** [comment]
Thanks for responding Zuzzas.
I have to look one more solutions to solve problem
